import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import Bottom from "./components/Bottom";
import Search from "./components/Search";
import Library from "./components/Library";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Open Spotify',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <main>
      <div className="h-screen w-screen flex bg-black">
        
<div className="w-1/4">
<Search></Search>
    <Library></Library>
    <Bottom></Bottom>
</div>
<div className="w-[73%]">
{children}
</div>

        </div>
    </main>
    </html>
  )
}
